Don't attempt to write on invalid input
OSGeo/shapelib pull request #5
Opened 2019-12-02 23:31 UTC by pramsey

Some DBF files are written without a record count (because, say
the SHP file or SHX file already give a record count. In that
case, checking the shape index being > number of records always
returns deleted, which is not correct.

2019-12-02 23:44 UTC, rouault commented
The commit message doesn't match what the code does. What are the situations where p == NULL or nmemb == 0 ?

2019-12-02 23:46 UTC, pramsey commented
Just blindly getting our software running again... https://github.com/postgis/postgis/commit/00eb4b44b4e8b7c98d8b9cbc611aa496812b33ee#diff-7dca6e3da1ca13b272669d5646bcf00bL118

2022-03-19 22:17 UTC, r-barnes commented
This looks reasonable to me.

2024-03-09 16:06 UTC, thbeu requested changes
I'd claim this should not be merged:

* It's not consistent throughout all I/O hook functions.
* You can define your own hook function for `FWrite` to fix it on the caller side.

2024-08-13 14:40 UTC, thbeu commented
@rouault Once again, I propose to close this PR without merging.

2024-08-13 14:47 UTC, closed without merging